# Estructuras de datos con R

 Esta actividad tiene como objetivo evaluar la comprensión del manejo y manipulación de estructuras de datos fundamentales en R, como son los vectores, matrices, listas y dataframes. A través de los ejercicios se evaluará la familiarización con las operaciones básicas en R, manipulación de estructuras de datos y funciones comunes

 1. Dada una serie de objetos en R (32, "R es divertido", TRUE, 2.5), identifica el tipo de dato de cada uno.

In [1]:
obj1 <- 32
obj2 <- "R es divertido"
obj3 <- TRUE
obj4 <- 2.5

cat("1. Tipos de datos:\n")
cat("32:", typeof(obj1), "\n")
cat("'R es divertido':", typeof(obj2), "\n")
cat("TRUE:", typeof(obj3), "\n")
cat("2.5:", typeof(obj4), "\n\n")

1. Tipos de datos:
32: double 
'R es divertido': character 
TRUE: logical 
2.5: double 



2. Convierte el número 4.5 a tipo entero y la cadena "100" a tipo numérico.

In [2]:
num_entero <- as.integer(4.5)
cadena <- as.numeric("100")
cat("2. Conversiones:\n")
cat("4.5 a entero:", num_entero, "\n")
cat("'100' a numérico:", cadena, "\n\n")

2. Conversiones:
4.5 a entero: 4 
'100' a numérico: 100 



   
3. Crea un vector que contenga un número, una cadena y un valor lógico. Luego, verifica el tipo de dato del vector.
 

In [3]:
vector_mixto <- c(42, "texto", TRUE)
cat("3. Vector mixto:", vector_mixto, "\n")
cat("Tipo del vector:", typeof(vector_mixto), "\n\n")

3. Vector mixto: 42 texto TRUE 
Tipo del vector: character 



4. Dado el valor NA, utiliza diversas funciones is.* para determinar si es NA, numeric, character, o logical.

In [4]:
valor_na <- NA
cat("4. Evaluación de NA:\n")
cat("is.na(NA):", is.na(valor_na), "\n")
cat("is.numeric(NA):", is.numeric(valor_na), "\n")
cat("is.character(NA):", is.character(valor_na), "\n")
cat("is.logical(NA):", is.logical(valor_na), "\n\n")

4. Evaluación de NA:
is.na(NA): TRUE 
is.numeric(NA): FALSE 
is.character(NA): FALSE 
is.logical(NA): TRUE 



5. Crea un factor con tres niveles ("bajo", "medio", "alto") y luego añade un nuevo nivel "muy alto".

In [1]:
factor_niveles <- factor(c("bajo", "medio", "alto"))
levels(factor_niveles) <- c(levels(factor_niveles), "muy alto")
cat("5. Factor con niveles:\n")
print(factor_niveles)
cat("Niveles:", levels(factor_niveles), "\n\n")

5. Factor con niveles:
[1] bajo  medio alto 
Levels: alto bajo medio muy alto
Niveles: alto bajo medio muy alto 



6. Crea dos vectores numéricos y realiza una operación de suma entre ellos.

In [6]:
vec1 <- c(1, 2, 3, 4, 5)
vec2 <- c(10, 20, 30, 40, 50)
suma_vectores <- vec1 + vec2
cat("6. Suma de vectores:\n")
cat("Vector 1:", vec1, "\n")
cat("Vector 2:", vec2, "\n")
cat("Suma:", suma_vectores, "\n\n")

6. Suma de vectores:
Vector 1: 1 2 3 4 5 
Vector 2: 10 20 30 40 50 
Suma: 11 22 33 44 55 



7. Dado un vector numérico, extrae los elementos en las posiciones 2, 4, y 6.

In [7]:
vector <- c(10, 20, 30, 40, 50, 60, 70, 80)
elementos <- vector[c(2, 4, 6)]
cat("7. Elementos en posiciones 2, 4, 6:", elementos, "\n\n")

7. Elementos en posiciones 2, 4, 6: 20 40 60 



8. Crea una matriz de 3 3 con números secuenciales del 1 al 9.

In [8]:
matriz_3x3 <- matrix(1:9, nrow = 3, ncol = 3)
cat("8. Matriz 3x3:\n")
print(matriz_3x3)
cat("\n")

8. Matriz 3x3:
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9



9. Realiza la transposición de la matriz creada en el ejercicio anterior.

In [9]:
matriz_transpuesta <- t(matriz_3x3)
cat("9. Matriz transpuesta:\n")
print(matriz_transpuesta)
cat("\n")

9. Matriz transpuesta:
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9



10.  Accede al elemento en la segunda fila, tercera columna de una matriz dada.

In [10]:
elemento <- matriz_3x3[2, 3]
cat("10. Elemento [2,3] de la matriz:", elemento, "\n\n")

10. Elemento [2,3] de la matriz: 8 



11.  Crea una lista en R que contenga un vector numérico, una matriz y un carácter.

In [2]:
lista_compleja <- list(
  vector = c(1, 2, 3, 4, 5),
  matriz = matrix(1:4, nrow = 2),
  char = "R"
)
cat("11. Lista creada:\n")
print(lista_compleja)
cat("\n")

11. Lista creada:


$vector
[1] 1 2 3 4 5

$matriz
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$char
[1] "R"




12.  Dada una lista, accede al tercer elemento de la misma.

In [11]:
tercer_elemento <- lista_compleja[[3]]
cat("12. Tercer elemento de la lista:", tercer_elemento, "\n\n")

12. Tercer elemento de la lista: R 



13.  Añade un nuevo elemento a una lista existente y luego elimina el segundo elemento.

In [13]:
lista_compleja$nuevo <- "Elemento nuevo"
lista_compleja[[2]] <- NULL
cat("13. Lista modificada:\n")
print(lista_compleja)
cat("\n")

13. Lista modificada:
$vector
[1] 1 2 3 4 5

$char
[1] "R"

$nuevo
[1] "Elemento nuevo"




14.  Crea un dataframe con dos columnas: una con nombres de personas y otra con sus edades.

In [14]:
df_personas <- data.frame(
  nombre = c("Ana", "Carlos", "María", "Juan", "Laura"),
  edad = c(25, 30, 28, 35, 22)
)
cat("14. Dataframe de personas:\n")
print(df_personas)
cat("\n")

14. Dataframe de personas:
  nombre edad
1    Ana   25
2 Carlos   30
3  María   28
4   Juan   35
5  Laura   22



15. Selecciona la columna de edades del dataframe creado en el ejercicio anterior.

In [15]:
edades_col <- df_personas$edad
cat("15. Columna de edades:", edades_col, "\n\n")

15. Columna de edades: 25 30 28 35 22 



16.  Crea dos vectores, uno con nombres y otro con edades, y combínalos en un dataframe.

In [16]:
nombres_vec <- c("Pedro", "Sofía", "Diego", "Elena")
edades_vec <- c(27, 31, 29, 26)
df_combinado <- data.frame(nombre = nombres_vec, edad = edades_vec)
cat("16. Dataframe combinado:\n")
print(df_combinado)
cat("\n")

16. Dataframe combinado:
  nombre edad
1  Pedro   27
2  Sofía   31
3  Diego   29
4  Elena   26



17.  Utiliza la función apply para calcular la suma de cada fila en una matriz dada.

In [17]:
matriz_ejemplo <- matrix(1:12, nrow = 3, ncol = 4)
suma_filas <- apply(matriz_ejemplo, 1, sum)
cat("17. Matriz:\n")
print(matriz_ejemplo)
cat("Suma de filas:", suma_filas, "\n\n")

17. Matriz:
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12
Suma de filas: 22 26 30 



18.  Convierte un dataframe dado en una matriz.

In [5]:
df_temp <- data.frame(x = 1:3, y = 4:6, z = 7:9)
matriz_desde_df <- as.matrix(df_temp)
cat("18. Matriz desde dataframe:\n")
print(matriz_desde_df)
cat("\n")

18. Matriz desde dataframe:
     x y z
[1,] 1 4 7
[2,] 2 5 8
[3,] 3 6 9



19.  Añade una lista como una nueva columna en un dataframe existente.

In [6]:
df_personas <- data.frame(
  nombre = c("Ana", "Carlos", "María", "Juan", "Laura"),
  edad = c(25, 30, 28, 35, 22)
)
df_personas$hobbies <- list(
  c("leer", "nadar"),
  c("correr", "cocinar"),
  c("pintar"),
  c("música", "viajar"),
  c("cine", "deportes")
)
cat("19. Dataframe con lista como columna:\n")
print(df_personas)
cat("\n")

19. Dataframe con lista como columna:
  nombre edad         hobbies
1    Ana   25     leer, nadar
2 Carlos   30 correr, cocinar
3  María   28          pintar
4   Juan   35  música, viajar
5  Laura   22  cine, deportes


20.  Crea un vector con valores lógicos y utiliza funciones como any() y all() para evaluar los valores.

In [20]:
vector <- c(TRUE, FALSE, TRUE, TRUE, FALSE)
cat("20. Vector lógico:", vector, "\n")
cat("any() - ¿Alguno es TRUE?:", any(vector), "\n")
cat("all() - ¿Todos son TRUE?:", all(vector), "\n\n")

20. Vector lógico: TRUE FALSE TRUE TRUE FALSE 
any() - ¿Alguno es TRUE?: TRUE 
all() - ¿Todos son TRUE?: FALSE 



21.  Crea variables para almacenar un número entero, un número decimal (flotante), un carácter (cadena de texto), y un valor lógico. Luego, utiliza la función class() para imprimir el tipo de cada variable.

In [21]:
entero <- 42L
decimal <- 3.14
char <- "Hola R"
logic <- FALSE
cat("21. Tipos de variables:\n")
cat("Entero:", class(entero), "\n")
cat("Decimal:", class(decimal), "\n")
cat("Character:", class(char), "\n")
cat("Lógico:", class(logic), "\n\n")

21. Tipos de variables:
Entero: integer 
Decimal: numeric 
Character: character 
Lógico: logical 



22.  Genera un vector llamado edades que contenga las edades de cinco personas. Calcula la edad promedio utilizando la función mean().

In [22]:
edades <- c(18, 25, 32, 28, 45)
promedio_edad <- mean(edades)
cat("22. Edades:", edades, "\n")
cat("Promedio:", promedio_edad, "\n\n")

22. Edades: 18 25 32 28 45 
Promedio: 29.6 



23.  Crea dos vectores numéricos, a y b, con 5 elementos cada uno. Realiza la suma, resta, multiplicación y división elemento a elemento y guarda los resultados en nuevos vectores.

In [23]:
a <- c(10, 20, 30, 40, 50)
b <- c(2, 4, 6, 8, 10)
suma <- a + b
resta <- a - b
multi <- a * b
division <- a / b
cat("23. Operaciones vectoriales:\n")
cat("Suma:", suma, "\n")
cat("Resta:", resta, "\n")
cat("Multiplicación:", multi, "\n")
cat("División:", division, "\n\n")

23. Operaciones vectoriales:
Suma: 12 24 36 48 60 
Resta: 8 16 24 32 40 
Multiplicación: 20 80 180 320 500 
División: 5 5 5 5 5 



24.  Construye una matriz de 4x4 con números secuenciales y luego extrae la segunda fila completa y la tercera columna completa utilizando la indexación.

In [24]:
matriz_4x4 <- matrix(1:16, nrow = 4, ncol = 4)
fila_2 <- matriz_4x4[2, ]
columna_3 <- matriz_4x4[, 3]
cat("24. Matriz 4x4:\n")
print(matriz_4x4)
cat("Segunda fila:", fila_2, "\n")
cat("Tercera columna:", columna_3, "\n\n")

24. Matriz 4x4:
     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    6   10   14
[3,]    3    7   11   15
[4,]    4    8   12   16
Segunda fila: 2 6 10 14 
Tercera columna: 9 10 11 12 



25.  Dada una matriz de 3x3, reemplaza todos los elementos de la fila 2 por 0.

In [25]:
matriz_ejemplo2 <- matrix(1:9, nrow = 3, ncol = 3)
matriz_ejemplo2[2, ] <- 0
cat("25. Matriz con fila 2 en ceros:\n")
print(matriz_ejemplo2)
cat("\n")

25. Matriz con fila 2 en ceros:
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    0    0    0
[3,]    3    6    9



26.  Crea una lista llamada datos_personales que contenga tu nombre, tu edad y tus hobbies. Accede al elemento que contiene tus hobbies e imprímelo.

In [26]:
datos_personales <- list(
  nombre = "Roberto",
  edad = 28,
  hobbies = c("programación", "lectura", "senderismo")
)
cat("26. Hobbies:", datos_personales$hobbies, "\n\n")

26. Hobbies: programación lectura senderismo 



27.  A la lista anterior, añade un nuevo elemento que contenga tu color favorito. Luego, elimina el elemento que contiene tu edad.

In [27]:
datos_personales$color_favorito <- "azul"
datos_personales$edad <- NULL
cat("27. Datos personales modificados:\n")
print(datos_personales)
cat("\n")

27. Datos personales modificados:
$nombre
[1] "Roberto"

$hobbies
[1] "programación" "lectura"      "senderismo"  

$color_favorito
[1] "azul"




28.  Construye un dataframe df_personas con tres columnas: nombre, edad, y ciudad para cinco personas. Utiliza nombres, edades y ciudades de tu elección.

In [15]:
df_personas <- data.frame(
  nombre = c("Ana", "Carlos", "María", "Juan", "Laura"),
  edad = c(23, 30, 28, 35, 22),
  ciudad = c("Madrid", "Barcelona", "Valencia", "Sevilla", "Bilbao")
)
cat("28. Dataframe de personas:\n")
print(df_personas)
cat("\n")

28. Dataframe de personas:
  nombre edad    ciudad
1    Ana   23    Madrid
2 Carlos   30 Barcelona
3  María   28  Valencia
4   Juan   35   Sevilla
5  Laura   22    Bilbao



29.  Del dataframe anterior, selecciona solo las filas de las personas mayores de 25 años y crea un nuevo dataframe llamado df_mayores_25.

In [29]:
df_mayores_25 <- df_personas[df_personas$edad > 25, ]
cat("29. Personas mayores de 25:\n")
print(df_mayores_25)
cat("\n")

29. Personas mayores de 25:
  nombre edad    ciudad
2 Carlos   30 Barcelona
3  María   28  Valencia
4   Juan   35   Sevilla



30.  Añade una nueva columna al dataframe df_personas llamada email y rellénala con direcciones de correo electrónico ficticias para cada persona

In [30]:
df_personas$email <- c(
  "ana@email.com",
  "carlos@email.com",
  "maria@email.com",
  "juan@email.com",
  "laura@email.com"
)
cat("30. Dataframe con columna email:\n")
print(df_personas)

30. Dataframe con columna email:
  nombre edad    ciudad            email
1    Ana   23    Madrid    ana@email.com
2 Carlos   30 Barcelona carlos@email.com
3  María   28  Valencia  maria@email.com
4   Juan   35   Sevilla   juan@email.com
5  Laura   22    Bilbao  laura@email.com
