# Estructura de control y manejo de datos con R

Esta actividad tiene como objetivo evaluar la comprensión de R, cubriendo temas específicos relacionados con estructuras de control, bucles y la aplicación de funciones a diferentes estructuras de datos.

## Estructura de control

1. Escribe un programa que use if y else para imprimir “Es positivo” si un número es mayor que 0, y “Es negativo o cero” de lo contrario.

In [36]:
numero <- sample(-3:3, 1)

cat("El numero", numero)

if (numero > 0) {
  cat(" es positivo")
} else {
  cat(" es negativo o cero")
}

El numero 3 es positivo

2. Utiliza if, else if, y else para clasificar un número como “negativo”, “cero”, o “positivo”.

In [37]:
numero <- sample(-3:3, 1)

cat("El numero", numero)

if (numero < 0) {
  cat(" es negativo")
} else if (numero == 0) {
  cat(" es cero")
} else {
  cat(" es positivo")
}

El numero -3 es negativo

3. Crea un script que use switch para imprimir el nombre del mes correspondiente a un número (1 = Enero, 2 = Febrero, etc.).

In [38]:
numero_mes <- sample(1:12, 1)

nombre_mes <- switch(
  numero_mes,
  "1" = "Enero",
  "2" = "Febrero",
  "3" = "Marzo",
  "4" = "Abril",
  "5" = "Mayo",
  "6" = "Junio",
  "7" = "Julio",
  "8" = "Agosto",
  "9" = "Septiembre",
  "10" = "Octubre",
  "11" = "Noviembre",
  "12" = "Diciembre",
  "Mes inválido"
)

cat("El mes #", numero_mes, "es el mes de", nombre_mes)

El mes # 1 es el mes de Enero

4. Utiliza if y else para verificar si una persona es mayor de edad (18 años o más). Imprime un mensaje apropiado.

In [39]:
edad <- sample(1:50, 1)

cat(edad, "años")

if (edad >= 18) {
  cat(" es mayor de edad")
} else {
  cat(" es menor de edad")
}

29 años es mayor de edad

5. Escribe un programa que use switch para asignar categorías de evaluación (A, B, C, D, F) basadas en un puntaje numérico.

In [40]:
score <- sample(1:100, 1)

category <- switch(
  as.character(floor(score / 10)),
  "10" = "A",
  "9" = "A",
  "8" = "B",
  "7" = "C",
  "6" = "D",
  "F"
)
cat("Calificación:\t", score, "\n")
cat("Categoría:\t", category)

Calificación:	 83 
Categoría:	 B

6. Crea un vector de números y utiliza ifelse para reemplazar todos los números negativos con 0.

In [41]:
vector_nums <- sample(-5:5, 10, replace = TRUE)
vector_sin_negativos <- ifelse(vector_nums < 0, 0, vector_nums)
cat("Vector original: \t", vector_nums)
cat("\nVector sin negativos: \t", vector_sin_negativos)

Vector original: 	 -3 -1 -4 4 1 -5 -2 5 3 3
Vector sin negativos: 	 0 0 0 4 1 0 0 5 3 3

7. Usa ifelse para crear un vector que indique “Par” o “Impar” para cada número en un vector dado.

In [42]:
vector_nums <- sample(1:100, 10, replace = TRUE)
par_impar <- ifelse(vector_nums %% 2 == 0, "Par", "Impar")
cat("Vector original: \t", vector_nums)
cat("\nVector par o impar: \t", par_impar)

Vector original: 	 84 43 34 70 68 50 4 42 94 86
Vector par o impar: 	 Par Impar Par Par Par Par Par Par Par Par

8. Transforma un vector de edades en un vector de categorías “Menor” y “Adulto” usando ifelse.

In [43]:
edades <- sample(1:75, 10, replace = TRUE)
categories <- ifelse(edades < 18, "Menor", "Adulto")
cat("Edades: \t\t", edades)
cat("\nVector mayor o menor: \t", categories)

Edades: 		 19 8 35 74 22 46 40 11 36 17
Vector mayor o menor: 	 Adulto Menor Adulto Adulto Adulto Adulto Adulto Menor Adulto Menor

9. Utiliza ifelse para identificar y marcar todos los valores por encima del promedio e un vector.

In [44]:
vector <- sample(1:75, 10, replace = TRUE)
promedio <- mean(vector)

encima_promedio <- ifelse(
  vector > promedio,
  "⬆️",
  "⬇️"
)

cat("Promedio: \t", promedio, "\n")
cat("Vector: \t", vector)
cat("\nEstatus: \t", encima_promedio)

Promedio: 	 43.4 
Vector: 	 56 18 34 65 73 40 75 11 44 18
Estatus: 	 ⬆️ ⬇️ ⬇️ ⬆️ ⬆️ ⬇️ ⬆️ ⬇️ ⬆️ ⬇️

10.  Escribe un script que utilice ifelse para convertir temperaturas de Celsius a Fahrenheit solo si están por debajo de 0C.

In [45]:
celsius <- sample(-15:25, 10, replace = TRUE)
fahrenheit <- ifelse(celsius < 0, celsius * 9 / 5 + 32, celsius)
cat(celsius, "\n")
cat(fahrenheit)

1 2 20 -14 25 24 11 -12 -4 -11 
1 2 20 6.8 25 24 11 10.4 24.8 12.2

11.  Utiliza un bucle for para imprimir los números del 1 al 10.

In [46]:
for (i in 1:10) {
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


12.  Escribe un bucle for que calcule la suma de los números en un vector.

In [47]:
vector <- sample(1:10, 5, replace = TRUE)
suma <- 0
for (i in vector) {
  suma <- suma + i
}
cat("vector:", vector)
cat("\nSuma total:", suma)

vector: 6 3 4 10 10
Suma total: 33

13.  Utiliza un bucle for para generar y imprimir los primeros 10 números de la secuencia de Fibonacci.

In [48]:
n <- 10
fib <- numeric(n)
fib[1] <- 0
fib[2] <- 1
for (i in 3:n) {
  fib[i] <- fib[i - 1] + fib[i - 2]
}
cat(fib)

0 1 1 2 3 5 8 13 21 34

14.  Crea un bucle for que itere sobre un vector y imprima solo los valores pares.

In [49]:
vector <- sample(1:20, 10, replace = TRUE)

cat("Vector:", vector)
cat("\nPares:\n")

for (num in vector) {
  if (num %% 2 == 0) {
    cat(num, "\n")
  }
}

Vector: 18 17 11 20 9 1 7 17 8 20
Pares:
18 
20 
8 
20 


15.  Escribe un bucle for para calcular el factorial de un número.

In [50]:
numero <- sample(1:6, 1)
factorial <- 1

for (i in 1:numero) {
  factorial <- factorial * i
}

cat("Factorial de", numero, "es", factorial)

Factorial de 3 es 6

16.  Utiliza un bucle while para encontrar el menor número divisible por todos los números del 1 al 10.

In [51]:
numero <- 1
encontrado <- FALSE
while (!encontrado) {
  divisible <- TRUE
  for (i in 1:10) {
    if (numero %% i != 0) {
      divisible <- FALSE
      break
    }
  }
  if (divisible) {
    encontrado <- TRUE
  } else {
    numero <- numero + 1
  }
}
cat("El menor número divisible por todos del 1 al 10 es:", numero)

El menor número divisible por todos del 1 al 10 es: 2520

17.  Escribe un bucle while que imprima “Hola” 5 veces.

In [52]:
contador <- 1
while (contador <= 5) {
  cat("Hola\n")
  contador <- contador + 1
}

Hola
Hola
Hola
Hola
Hola


18.  Crea un bucle while para sumar números hasta que la suma exceda 100.

In [ ]:
suma <- 0
numero <- 1

while (suma <= 100) {
  suma <- suma + numero
  numero <- numero + 1
}

cat("La suma es:", suma)

La suma es: 105

19.  Utiliza un bucle while para encontrar y imprimir el primer número cuadrado perfecto mayor que 100.

In [ ]:
numero <- 1

while (numero^2 <= 100) {
  numero <- numero + 1
}

cat("El primer cuadrado perfecto mayor que 100 es:", numero^2)

El primer cuadrado perfecto mayor que 100 es: 121

20. Escribe un bucle while que lea números del usuario hasta que ingresen un 0, luego imprime la suma de esos números.

In [ ]:
nums <- c()
numero <- -1

while (numero != 0) {
  numero <- as.numeric(readline("Ingresa un número (0 para terminar): "))

  if (numero != 0) {
    nums <- c(nums, numero)
  }
}

cat("Números ingresados:\n")
cat(nums)

cat("\nLa suma es:", sum(nums), "\n")

Números ingresados:
1 2 3 4 5
La suma es: 15 


21.  Utiliza un bucle repeat para imprimir los primeros 5 números naturales, luego usa break para salir del bucle.

In [62]:
contador <- 1

repeat {
  cat(contador, "\n")
  contador <- contador + 1
  if (contador > 5) {
    break
  }
}

1 
2 
3 
4 
5 


22.  Escribe un bucle repeat que encuentre el factorial de un número. Utiliza break para terminar el bucle cuando sea apropiado.

In [70]:
numero <- sample(1:6, 1)
factorial <- 1
i <- 1
repeat {
  factorial <- factorial * i
  i <- i + 1
  if (i > numero) {
    break
  }
}
cat("Factorial de", numero, "es", factorial)

Factorial de 6 es 720

23.  Crea un bucle repeat que solicite al usuario números y los sume hasta que el usuario ingrese un número negativo.

In [72]:
nums_entrada <- c()
suma <- 0

repeat {
  numero <- as.numeric(readline("Ingresa un número (negativo para terminar): "))

  if (numero < 0) {
    break
  }

  nums_entrada <- c(nums_entrada, numero)
  suma <- suma + numero
}

cat("Los números ingresados fueron:\n")
cat(nums_entrada)

cat("\nLa suma es:", suma, "\n")

Los números ingresados fueron:
12 3 4 5
La suma es: 24 


24.  Utiliza un bucle repeat para generar números aleatorios hasta obtener un número mayor que 0.95, luego imprime el número de intentos realizados.

In [74]:
intentos <- 0
repeat {
  numero <- runif(1)
  intentos <- intentos + 1
  if (numero > 0.95) {
    break
  }
}
cat("Número de intentos:", intentos)
cat("\nNúmero obtenido:", numero)

Número de intentos: 29
Número obtenido: 0.952779

25.  Implementa un bucle repeat que itere hasta que la diferencia entre dos estimaciones consecutivas de pi (usando la serie de Leibniz) sea menor a un umbral específico. La serie de Leibniz para el cálculo de se define como:

![25_image](image.png)

In [77]:
pi_estimado <- 0
pi_anterior <- 0
umbral <- 0.0001
n <- 0
repeat {
  pi_anterior <- pi_estimado
  termino <- ((-1)^n) / (2 * n + 1)
  pi_estimado <- pi_estimado + termino
  n <- n + 1
  if (abs(4 * pi_estimado - 4 * pi_anterior) < umbral && n > 1) {
    break
  }
}
cat("Estimación de pi:", 4 * pi_estimado)
cat("\nIteraciones:", n)

Estimación de pi: 3.141643
Iteraciones: 20001

26.  Utiliza bucles anidados for para imprimir una tabla de multiplicar del 1 al 10.

In [2]:
for (i in 1:10) {
  for (j in 1:10) {
    cat(i * j, "\t")
  }
  cat("\n")
}

1 	2 	3 	4 	5 	6 	7 	8 	9 	10 	
2 	4 	6 	8 	10 	12 	14 	16 	18 	20 	
3 	6 	9 	12 	15 	18 	21 	24 	27 	30 	
4 	8 	12 	16 	20 	24 	28 	32 	36 	40 	
5 	10 	15 	20 	25 	30 	35 	40 	45 	50 	
6 	12 	18 	24 	30 	36 	42 	48 	54 	60 	
7 	14 	21 	28 	35 	42 	49 	56 	63 	70 	
8 	16 	24 	32 	40 	48 	56 	64 	72 	80 	
9 	18 	27 	36 	45 	54 	63 	72 	81 	90 	
10 	20 	30 	40 	50 	60 	70 	80 	90 	100 	


27.  Escribe un programa con bucles anidados while para encontrar pares de números cuya suma sea 100.

In [4]:
i <- 1
while (i <= 50) {
  j <- 1
  while (j <= 100) {
    if (i + j == 100) {
      cat(i, "+", j, "= 100\n")
    }
    j <- j + 1
  }
  i <- i + 1
}

1 + 99 = 100
2 + 98 = 100
3 + 97 = 100
4 + 96 = 100
5 + 95 = 100
6 + 94 = 100
7 + 93 = 100
8 + 92 = 100
9 + 91 = 100
10 + 90 = 100
11 + 89 = 100
12 + 88 = 100
13 + 87 = 100
14 + 86 = 100
15 + 85 = 100
16 + 84 = 100
17 + 83 = 100
18 + 82 = 100
19 + 81 = 100
20 + 80 = 100
21 + 79 = 100
22 + 78 = 100
23 + 77 = 100
24 + 76 = 100
25 + 75 = 100
26 + 74 = 100
27 + 73 = 100
28 + 72 = 100
29 + 71 = 100
30 + 70 = 100
31 + 69 = 100
32 + 68 = 100
33 + 67 = 100
34 + 66 = 100
35 + 65 = 100
36 + 64 = 100
37 + 63 = 100
38 + 62 = 100
39 + 61 = 100
40 + 60 = 100
41 + 59 = 100
42 + 58 = 100
43 + 57 = 100
44 + 56 = 100
45 + 55 = 100
46 + 54 = 100
47 + 53 = 100
48 + 52 = 100
49 + 51 = 100
50 + 50 = 100


28.  Crea un script que utilice bucles anidados para generar combinaciones de dos vectores.

In [7]:
vector1 <- c("A", "B", "C")
vector2 <- c(1, 2, 3)
for (i in vector1) {
  for (j in vector2) {
    cat(i, j, "\n")
  }
}

A 1 
A 2 
A 3 
B 1 
B 2 
B 3 
C 1 
C 2 
C 3 


29.  Utiliza bucles anidados para dibujar un patrón simple de asteriscos (por ejemplo, un cuadrado o triángulo).

In [8]:
filas <- 5
for (i in 1:filas) {
  for (j in 1:i) {
    cat("*")
  }
  cat("\n")
}

*
**
***
****
*****


30.  Implementa un bucle anidado para calcular el producto cartesiano de dos conjuntos almacenados en vectores.

In [9]:
conjunto1 <- c(1, 2, 3)
conjunto2 <- c("X", "Y")
producto_cartesiano <- list()
k <- 1
for (i in conjunto1) {
  for (j in conjunto2) {
    producto_cartesiano[[k]] <- c(i, j)
    k <- k + 1
  }
}
print(producto_cartesiano)

[[1]]
[1] "1" "X"

[[2]]
[1] "1" "Y"

[[3]]
[1] "2" "X"

[[4]]
[1] "2" "Y"

[[5]]
[1] "3" "X"

[[6]]
[1] "3" "Y"



## Manejo de datos

1. Utiliza lapply para convertir todos los caracteres en una lista de cadenas a mayúsculas.

In [10]:
lista_cadenas <- list("hola", "mundo", "r", "programación")
uppercase <- lapply(lista_cadenas, toupper)
print(uppercase)

[[1]]
[1] "HOLA"

[[2]]
[1] "MUNDO"

[[3]]
[1] "R"

[[4]]
[1] "PROGRAMACIÓN"



2. Escribe un script que use sapply para calcular la media de cada vector en una lista.

In [11]:
lista_vectores <- list(c(1, 2, 3, 4, 5), c(10, 20, 30), c(5, 15, 25, 35))
medias <- sapply(lista_vectores, mean)
print(medias)

[1]  3 20 20


3. Utiliza vapply para verificar si los elementos en una lista de vectores son todos positivos, devolviendo un vector lógico.

In [16]:
lista_nums <- list(c(1, 2, 3), c(-1, 2, 3), c(5, 10, 15))
todos_positivos <- vapply(lista_nums, function(x) all(x > 0), logical(1))
print(todos_positivos)

[1]  TRUE FALSE  TRUE


4. Implementa lapply para dividir cada número en una lista de vectores por su máximo valor.

In [18]:
lista_datos <- list(c(10, 20, 30, 40), c(5, 15, 25), c(100, 200, 300))
nums <- lapply(lista_datos, function(x) x / max(x))
print(nums)

[[1]]
[1] 0.25 0.50 0.75 1.00

[[2]]
[1] 0.2 0.6 1.0

[[3]]
[1] 0.3333333 0.6666667 1.0000000



5. Usa sapply para contar cuántos elementos únicos hay en cada vector de una lista.

In [19]:
lista_con_duplicados <- list(c(1, 1, 2, 3, 3), c(5, 5, 5, 10), c(1, 2, 3, 4, 5))
unique <- sapply(lista_con_duplicados, function(x) length(unique(x)))
print(unique)

[1] 3 2 5


6. Utiliza apply para sumar los valores en cada fila de una matriz.

In [24]:
matriz <- matrix(1:12, nrow = 3, ncol = 4)
print("Matriz:")
print(matriz)
suma_filas <- apply(matriz, 1, sum)
print("Suma por fila:")
print(suma_filas)

[1] "Matriz:"


     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12
[1] "Suma por fila:"
[1] 22 26 30


7. Escribe un script que use apply para normalizar (restar la media y dividir por la desviación estándar) las columnas de una matriz.

In [25]:
matriz <- matrix(rnorm(20), nrow = 5, ncol = 4)
print("Matriz original:")
print(matriz)
matriz_normalizada <- apply(matriz, 2, function(x) (x - mean(x)) / sd(x))
print("Matriz normalizada:")
print(matriz_normalizada)

[1] "Matriz original:"
            [,1]       [,2]       [,3]       [,4]
[1,]  0.47845196  0.3507083 1.62462720 -0.1661227
[2,] -1.32294877 -1.6658972 0.09465819 -0.9484122
[3,]  0.12505699 -0.6690468 0.73606898 -0.3913855
[4,] -0.08386431  1.6417791 0.44376341 -1.5301404
[5,]  0.49665319  0.3028644 0.48438848  0.3672427
[1] "Matriz normalizada:"
            [,1]       [,2]       [,3]       [,4]
[1,]  0.72298815  0.2896325  1.6426118  0.5035771
[2,] -1.68982112 -1.3390094 -1.0085923 -0.5679660
[3,]  0.24964834 -0.5339375  0.1028753  0.1950228
[4,] -0.03018237  1.3323213 -0.4036459 -1.3647896
[5,]  0.74736701  0.2509930 -0.3332488  1.2341556


8. Implementa apply para encontrar el valor máximo en cada capa de un array tridimensional.

In [26]:
array_3d <- array(1:24, dim = c(3, 4, 2))
print("Array 3D:")
print(array_3d)
max_capa <- apply(array_3d, 3, max)
print("Máximo por capa:")
print(max_capa)

[1] "Array 3D:"
, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

[1] "Máximo por capa:"
[1] 12 24


9. Usa apply para convertir todas las temperaturas en una matriz de Celsius a Fahrenheit.

In [ ]:
matriz_celsius <- matrix(c(0, 10, 20, 30, 15, 25, 35, 5), nrow = 2, ncol = 4)
print("Temperaturas en Celsius:")
print(matriz_celsius)
matriz_fahrenheit <- apply(matriz_celsius, c(1, 2), function(x) x * 9 / 5 + 32)
print("Temperaturas en Fahrenheit:")
print(matriz_fahrenheit)

[1] "Temperaturas en Celsius:"
     [,1] [,2] [,3] [,4]
[1,]    0   20   15   35
[2,]   10   30   25    5
[1] "Temperaturas en Fahrenheit:"
     [,1] [,2] [,3] [,4]
[1,]   32   68   59   95
[2,]   50   86   77   41


10. Crea una función personalizada y úsala con apply para calcular el rango (máximo - mínimo) de los valores en las filas de una matriz

In [28]:
calcular_rango <- function(x) {
  max(x) - min(x)
}
matriz <- matrix(c(1, 5, 10, 2, 8, 15, 3, 12, 20), nrow = 3, ncol = 3)
print("Matriz:")
print(matriz)
rangos <- apply(matriz, 1, calcular_rango)
print("Rango por fila:")
print(rangos)

[1] "Matriz:"
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    5    8   12
[3,]   10   15   20
[1] "Rango por fila:"
[1]  2  7 10
